name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends=2019.03
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.7
  - anaconda-project=0.8.4
  - anyqt=0.0.10
  - argh=0.26.2
  - asn1crypto=1.2.0
  - astroid=2.3.3
  - astropy=3.2.3
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - autopep8=1.4.4
  - babel=2.7.0
  - backcall=0.1.0
  - backports=1.0
  - backports.os=0.1.1
  - backports.shutil_get_terminal_size=1.0.0
  - bcrypt=3.1.7
  - beautifulsoup4=4.8.1
  - bitarray=1.1.0
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.16.3
  - bokeh=1.4.0
  - boto=2.49.0
  - bottleneck=1.3.1
  - bzip2=1.0.8
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.2.2
  - clyent=1.2.2
  - colorama=0.4.1
  - conda=4.8.0
  - conda-build=3.17.8
  - conda-env=2.6.0
  - conda-package-handling=1.6.0
  - conda-verify=3.1.1
  - console_shortcut=0.1.1
  - contextlib2=0.6.0.post1
  - cryptography=2.8
  - curl=7.67.0
  - cycler=0.10.0
  - cython=0.29.14
  - cytoolz=0.10.1
  - dask=2.9.0
  - dask-core=2.9.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - diff-match-patch=20181111
  - distributed=2.9.0
  - docutils=0.15.2
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - fastcache=1.1.0
  - fasttsne=0.2.13
  - filelock=3.0.12
  - flake8=3.7.9
  - flask=1.1.1
  - freetype=2.9.1
  - fsspec=0.6.0
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=1.4.0
  - glob2=0.7
  - greenlet=0.4.15
  - h5py=2.9.0
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.8
  - imageio=2.6.1
  - imagesize=1.1.0
  - importlib_metadata=1.2.0
  - intel-openmp=2019.4
  - intervaltree=3.0.2
  - ipykernel=5.1.3
  - ipython=7.10.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.14.1
  - jinja2=2.10.3
  - joblib=0.14.0
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.1
  - jupyterlab=1.2.3
  - jupyterlab_server=1.0.6
  - keyring=19.2.0
  - keyrings.alt=3.1.1
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - lazy-object-proxy=1.4.3
  - libarchive=3.3.3
  - libcurl=7.67.0
  - libiconv=1.15
  - liblief=0.9.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libspatialindex=1.9.3
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvmlite=0.30.0
  - locket=0.2.0
  - lxml=4.4.2
  - lz4-c=1.8.1.2
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mock=3.0.5
  - more-itertools=7.2.0
  - mpmath=1.1.0
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - networkx=2.4
  - nltk=3.4.5
  - nose=1.3.7
  - notebook=6.0.2
  - numba=0.46.0
  - numexpr=2.7.0
  - numpy=1.17.4
  - numpy-base=1.17.4
  - numpydoc=0.9.1
  - olefile=0.46
  - openpyxl=3.0.2
  - openssl=1.1.1d
  - orange3=3.19.0
  - packaging=19.2
  - pandas=0.25.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - paramiko=2.6.0
  - parso=0.5.1
  - partd=1.1.0
  - path.py=12.0.2
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - patsy=0.5.1
  - pep8=1.7.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=19.3.1
  - pkginfo=1.5.0.1
  - pluggy=0.13.1
  - ply=3.11
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - psutil=5.6.7
  - py=1.8.0
  - py-lief=0.9.0
  - pycodestyle=2.5.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pycrypto=2.6.1
  - pycurl=7.43.0.3
  - pydocstyle=4.0.1
  - pyflakes=2.1.1
  - pygments=2.5.2
  - pylint=2.4.4
  - pympler=0.7
  - pynacl=1.3.0
  - pyodbc=4.0.27
  - pyopenssl=19.1.0
  - pyparsing=2.4.5
  - pyqt=5.9.2
  - pyqtgraph=0.10.0
  - pyreadline=2.1
  - pyrsistent=0.15.6
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=5.3.1
  - pytest-arraydiff=0.3
  - pytest-astropy=0.6.0
  - pytest-astropy-header=0.1.1
  - pytest-doctestplus=0.5.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.2
  - python=3.7.3
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.2
  - python-language-server=0.31.2
  - python-libarchive-c=2.8
  - python-louvain=0.13
  - pytz=2019.3
  - pywavelets=1.1.1
  - pywin32-ctypes=0.2.0
  - pyyaml=5.1.2
  - pyzmq=18.1.0
  - qdarkstyle=2.7
  - qt=5.9.7
  - qtawesome=0.6.0
  - qtconsole=4.6.0
  - qtpy=1.9.0
  - requests=2.22.0
  - rope=0.14.0
  - rtree=0.8.3
  - ruamel_yaml=0.15.46
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.2
  - seaborn=0.9.0
  - send2trash=1.5.0
  - serverfiles=0.3.0
  - setuptools=42.0.2
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.13.0
  - snappy=1.1.7
  - snowballstemmer=2.0.0
  - sortedcollections=1.1.2
  - sortedcontainers=2.1.0
  - soupsieve=1.9.5
  - sphinx=2.2.2
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - sphinxcontrib-websupport=1.1.2
  - spyder=4.0.0
  - spyder-kernels=1.8.1
  - sqlalchemy=1.3.11
  - sqlite=3.30.1
  - statsmodels=0.10.1
  - sympy=1.4
  - tblib=1.5.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.40.0
  - traitlets=4.3.3
  - ujson=1.35
  - unicodecsv=0.14.1
  - urllib3=1.25.7
  - watchdog=0.9.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xlrd=1.2.0
  - xlsxwriter=1.2.6
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - yapf=0.28.0
  - zeromq=4.3.1
  - zict=1.0.0
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - dill==0.3.0
    - geographiclib==1.49
    - geopy==1.20.0
    - gridcal==3.4.1
    - helpdev==0.6.10
    - mpi4py==3.0.2
    - poap==0.1.26
    - ptyprocess==0.6.0
    - pulp==1.6.10
    - pydoe==0.3.8
    - pydoe2==1.2.0
    - pyds==0.2.0
    - pyqt5==5.12.3
    - pyqt5-sip==12.7.0
    - pyqtwebengine==5.12.1
    - pyside2==5.13.0
    - pysot==0.2.2
    - shiboken2==5.13.0
    - smopy==0.0.7
    - spyder-notebook==0.1.4
    - typed-ast==1.4.0
